name: Deploy to GIthub pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    permissions:
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Steup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: dist
        name: github-pages

    - name: Deploy to another repository
      run: |
        git config --global user.name eccentricpark
        git config --global user.email pen40@naver.com
        git clone --branch gh-pages --single-branch https://${{ secrets.GITHUB_TOKEN }}@github.com/eccentricpark/eccentricpark.github.io.git gh-pages
        rsync -av --delete dist/ gh-pages/
        cd gh-pages
        git add .
        git commit -m "Deploy updated website"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    # - name: Deploy
    #   uses: actions/deploy-pages@v1
    #   with:
    #     token: ${{secrets.GITHUB_TOKEN}}
    #     repository-name: eccentricpark/eccentricpark.github.io
    #     branch: main
    #     folder: dist